# Generated by Django 4.2.5 on 2023-12-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='interview',
            name='start_date',
            field=models.DateField(),
        ),
    ]
