# Generated by Django 4.2.5 on 2023-12-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='application_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
