# Generated by Django 4.2.5 on 2023-12-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_interview_application_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='description',
            field=models.TextField(default=' ', max_length=1000),
        ),
    ]
