# Generated by Django 4.2.5 on 2024-01-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_interview_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
