# Generated by Django 4.2.5 on 2024-03-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='schedulded',
            field=models.BooleanField(default=False),
        ),
    ]
