# Generated by Django 4.2.5 on 2024-05-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_remove_user_answer_user_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_answer',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='user_answer',
            name='semantic_score',
            field=models.FloatField(default=0),
        ),
    ]
