# Generated by Django 4.2.5 on 2024-05-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_user_answer_user_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answer',
            name='user_answer',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
