# Generated by Django 4.2.5 on 2024-05-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_user_answer_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user_answers',
        ),
        migrations.AddField(
            model_name='report',
            name='user_answers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='company.user_answer'),
        ),
    ]
