# Generated by Django 4.2.5 on 2024-05-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_remove_report_user_answers_report_user_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user_answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='company.user_answer'),
        ),
    ]
