# Generated by Django 4.2.5 on 2024-05-07 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_remove_report_user_answers_report_user_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.interview'),
        ),
    ]
