# Generated by Django 4.2.5 on 2023-10-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='Name',
        ),
    ]
