# Generated by Django 4.2.5 on 2023-10-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidate_cv_alter_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, default='icons/icons/user-profile-edit.svg', null=True, upload_to='images/'),
        ),
    ]
