# Generated by Django 4.2.5 on 2023-10-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, default='images/user1.jpg', null=True, upload_to='images/'),
        ),
    ]
