# Generated by Django 4.2.5 on 2023-11-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_alter_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='desc',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
