# Generated by Django 4.2.5 on 2024-01-26 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_question_image'),
        ('candidate', '0006_candidate_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cv_uploads/')),
                ('applied_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.interview')),
            ],
        ),
    ]
