# Generated by Django 4.2.5 on 2024-03-04 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_cvsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsubmission',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ApprovedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
        ),
    ]
