# Generated by Django 4.2.5 on 2024-03-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_cvsubmission_show_approvedcandidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovedCandidate',
        ),
    ]
