# Generated by Django 4.2.5 on 2024-03-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_question_image'),
        ('candidate', '0009_delete_approvedcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.interview')),
            ],
        ),
    ]
