# Generated by Django 4.2.5 on 2024-03-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_approvedcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsubmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
    ]
