# Generated by Django 4.2.5 on 2024-05-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_cvsubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsubmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='Pending', max_length=20),
        ),
    ]
